# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('app', models.CharField(max_length=128)),
                ('apm', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=128)),
                ('fecha_nac', models.DateField(max_length=128)),
                ('edad', models.IntegerField(max_length=128)),
                ('sexo', models.BooleanField(max_length=128)),
                ('passw', models.CharField(max_length=256)),
            ],
        ),
    ]
