# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20161123_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.BooleanField(choices=[(True, 'Mujer'), (False, 'Hombre')]),
        ),
    ]
