# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apm',
        ),
    ]
